[package]
name = "blick"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
ash = "0.37.0"
ash-window = "0.12.0"
bitflags = "1.3.2"
gpu-allocator = "0.22.0"
hassle-rs = "0.10.0"
log = "0.4"
lru = "0.8.0"
raw-window-handle = "0.5"
rspirv-reflect = "0.7.0"
winit = "0.28"
